// client/src/constants/bloodStockConstants.js
export const BLOOD_STOCK_LIST_REQUEST = 'BLOOD_STOCK_LIST_REQUEST';
export const BLOOD_STOCK_LIST_SUCCESS = 'BLOOD_STOCK_LIST_SUCCESS';
export const BLOOD_STOCK_LIST_FAIL = 'BLOOD_STOCK_LIST_FAIL';

export const BLOOD_STOCK_UPDATE_REQUEST = 'BLOOD_STOCK_UPDATE_REQUEST';
export const BLOOD_STOCK_UPDATE_SUCCESS = 'BLOOD_STOCK_UPDATE_SUCCESS';
export const BLOOD_STOCK_UPDATE_FAIL = 'BLOOD_STOCK_UPDATE_FAIL';
export const BLOOD_STOCK_UPDATE_RESET = 'BLOOD_STOCK_UPDATE_RESET';