// client/src/constants/bloodRequestConstants.js
export const BLOOD_REQUEST_CREATE_REQUEST = 'BLOOD_REQUEST_CREATE_REQUEST';
export const BLOOD_REQUEST_CREATE_SUCCESS = 'BLOOD_REQUEST_CREATE_SUCCESS';
export const BLOOD_REQUEST_CREATE_FAIL = 'BLOOD_REQUEST_CREATE_FAIL';
export const BLOOD_REQUEST_CREATE_RESET = 'BLOOD_REQUEST_CREATE_RESET';

export const BLOOD_REQUEST_LIST_REQUEST = 'BLOOD_REQUEST_LIST_REQUEST';
export const BLOOD_REQUEST_LIST_SUCCESS = 'BLOOD_REQUEST_LIST_SUCCESS';
export const BLOOD_REQUEST_LIST_FAIL = 'BLOOD_REQUEST_LIST_FAIL';

export const BLOOD_REQUEST_UPDATE_REQUEST = 'BLOOD_REQUEST_UPDATE_REQUEST';
export const BLOOD_REQUEST_UPDATE_SUCCESS = 'BLOOD_REQUEST_UPDATE_SUCCESS';
export const BLOOD_REQUEST_UPDATE_FAIL = 'BLOOD_REQUEST_UPDATE_FAIL';
export const BLOOD_REQUEST_UPDATE_RESET = 'BLOOD_REQUEST_UPDATE_RESET';

export const BLOOD_REQUEST_HISTORY_REQUEST = 'BLOOD_REQUEST_HISTORY_REQUEST';
export const BLOOD_REQUEST_HISTORY_SUCCESS = 'BLOOD_REQUEST_HISTORY_SUCCESS';
export const BLOOD_REQUEST_HISTORY_FAIL = 'BLOOD_REQUEST_HISTORY_FAIL';