// client/src/constants/donationConstants.js
export const DONATION_REQUEST_CREATE_REQUEST = 'DONATION_REQUEST_CREATE_REQUEST';
export const DONATION_REQUEST_CREATE_SUCCESS = 'DONATION_REQUEST_CREATE_SUCCESS';
export const DONATION_REQUEST_CREATE_FAIL = 'DONATION_REQUEST_CREATE_FAIL';
export const DONATION_REQUEST_CREATE_RESET = 'DONATION_REQUEST_CREATE_RESET';

export const DONATION_REQUEST_LIST_REQUEST = 'DONATION_REQUEST_LIST_REQUEST';
export const DONATION_REQUEST_LIST_SUCCESS = 'DONATION_REQUEST_LIST_SUCCESS';
export const DONATION_REQUEST_LIST_FAIL = 'DONATION_REQUEST_LIST_FAIL';

export const DONATION_REQUEST_UPDATE_REQUEST = 'DONATION_REQUEST_UPDATE_REQUEST';
export const DONATION_REQUEST_UPDATE_SUCCESS = 'DONATION_REQUEST_UPDATE_SUCCESS';
export const DONATION_REQUEST_UPDATE_FAIL = 'DONATION_REQUEST_UPDATE_FAIL';
export const DONATION_REQUEST_UPDATE_RESET = 'DONATION_REQUEST_UPDATE_RESET';

export const DONATION_HISTORY_REQUEST = 'DONATION_HISTORY_REQUEST';
export const DONATION_HISTORY_SUCCESS = 'DONATION_HISTORY_SUCCESS';
export const DONATION_HISTORY_FAIL = 'DONATION_HISTORY_FAIL';
